### ISSUE TITLE
CODMW2019 - LauncherAutoClose.ps1 script is trying to find process name codmw2019 instead of ModernWarfare

### ISSUE THREAD

**Issue by BlatantDecoy** [SteamGridDB/steamgriddb-manager#100]
### Issue:
Although the game launches fine, the LauncherAutoClose.ps1 script is failing to see it and getting stuck on "Waiting for game to start"
After closing the game the powershell script is still stuck waiting for the game to start so never stops saying that I'm playing the game, unless I kill the session manually.
This is because $game is being set to codmw2019 instead of ModernWarfare. So when it looks for the process it can not find it.

### Troubleshooting steps:
Confirmed that the script isn't getting stuck when launching Overwatch
Edited _$SteamDirectory/userdata/$SteamUserId/config/shortcuts.vdf_ to remove `-windowstyle hidden` from the launch options to see the script's progress (couldn't do this via Steam's GUI due to character limit)
Observed the script to see where it was hanging
Commented out the `-ErrorAction SilentlyContinue` from line 43 LauncherAutoClose.ps1 `$gameProcess = Get-Process $game -ErrorAction SilentlyContinue`
Observed the error

### User Solution:
Edit _$SteamDirectory/userdata/$SteamUserId/config/shortcuts.vdf_ change `-game \"codmw2019\"` to be `-game \"ModernWarfare\"`

Alternative Solution:
Add the following code line to LauncherAutoClose.ps1 anywhere before line 43
`If ($game = "codmw2019") {$game = "ModernWarfare"}`

**Comment by dukeayers** [comment]
@BlatantDecoy were you able to confirm that either of your solutions fixed the problem locally?

**Comment by BlatantDecoy** [comment]
@dukeayers Yes, both of my solutions worked.
You can download codmw2019 free as Warzone uses the same executable to launch.

**Comment by aranel616** [comment]
This is fixed in 320d1a181c8389f343c6148ea9fe2a6ef965b054.
