### ISSUE TITLE
"Installation Aborted - Setup was not completed successfully"

### ISSUE THREAD

**Issue by Psherman01** [SteamGridDB/steamgriddb-manager#119]
**Describe the bug**
I am unable to install the manager. I initially tried to install it to "C:\Program Files\SteamGridDB" but it said "installation aborted - Setup was not completed successfully" and my only option was to cancel installation. With that said, I opened up the installer again and it said that the program was installed and it would reinstall/upgrade, but the same result occurred. Also the installer was wrong, I checked Program Files and there was no SteamGridDB folder. I know that the problem isn't because I'm trying to install to Program Files, which you usually need admin privlideges to modify, because I'm running the install program as an administrator (and every other program installation I can think of has worked fine installing to Program Files _without_ running the program as an administrator)

**To Reproduce**
1. Go to https://www.steamgriddb.com/manager
2. Click the "Download v0.4.2" button
3. Open the file "SteamGridDB Manager Setup 0.4.2.exe" as an administrator
4. Click "install only for this user" and then the next button
5. Change the destination folder to "C:\Program Files\SteamGridDB"
6. Click install

**Expected behavior**
I expected the program to install to "C:\Program Files\SteamGridDB" and then I would be able to use the program

**Operating System**
 - Windows 10, 20H2

**Installed Launchers**
I have Epic Games Launcher and GOG Galaxy installed, but they're not part of the problem

**Screenshots**
![image](https://user-images.githubusercontent.com/4514313/104835240-253d3000-585a-11eb-9b92-c402adcfda28.png)

**Log**
N/A: Program not installed

**Comment by George22x** [comment]
I attempted to install the program to Program Files, got this bug too and then could not install it even to a different location. I had to clean SteamGridDB occurrence in the registry and then installation to the default Users folder worked.

**Comment by kongomongo** [comment]
I don't have the defaults handy, but "anyone" should default to Program Files folder whereas only for me should install to a personal folder, as program files needs admin privileges.

**Comment by Psherman01** [comment]
> I attempted to install the program to Program Files, got this bug too and then could not install it even to a different location. I had to clean SteamGridDB occurrences in the registry and then installation to the default Users folder worked.

Where can I find these registries so I can delete them?

**Comment by Psherman01** [comment]
> I attempted to install the program to Program Files, got this bug too and then could not install it even to a different location. I had to clean SteamGridDB occurrences in the registry and then installation to the default Users folder worked.

After deleting all the registry keys related to SteamGridDB in regedit, I reinstalled and now it works. Thanks!
