### ISSUE TITLE
Horizontal Grid Images in Big Picture

### ISSUE THREAD

**Issue by lolcatplays** [SteamGridDB/steamgriddb-manager#121]
**Describe the bug**
Horizontal Grid Images appear in the new launcher but not the Big Picture. When I use a program such as Steam Rom Manager or Steamgrid it is able to add these images

**To Reproduce**
1. Go to 'Horizontal Grid Images'
2. Click on any image
3. Hover over game box in steam
4. Image appears in new library view but not in big picture.

**Expected behavior**
The Image should appear in both the big picture and the horizontal grid view.

**Operating System**
 - Windows 10, 20H2

**Installed Launchers**
- Origin
- Uplay
- Steam

**Log**
[log.log](https://github.com/SteamGridDB/steamgriddb-manager/files/5889571/log.log)

**Comment by kongomongo** [comment]
You are running steamgriddb-manager without admin rights.

**Comment by lolcatplays** [comment]
God, thanks.. I have no idea why I didn't try that.
