### ISSUE TITLE
Freezes on grabbing games from Origin

### ISSUE THREAD

**Issue by axfelix** [SteamGridDB/steamgriddb-manager#124]
Whenever I try to run an import scan, the animation stops immediately on "grabbing games from Origin" and this is the last line in logs:

[2021-02-04 16:47:18.769] [info] Import: Started origin

Is there any way I can bypass this?

**Comment by kongomongo** [comment]
what does your log file say? It's usually located in %APPDATA%\Electron\log.log

**Comment by axfelix** [comment]
I was able to fix this by reinstalling Origin -- likely my install had some kind of edge case.

**Comment by kongomongo** [comment]
Alrighty. You can close this issue if you feel like it's resolved.
