### ISSUE TITLE
Games stop launching after using big picture

### ISSUE THREAD

**Issue by rorokapur** [SteamGridDB/steamgriddb-manager#156]
**Describe the bug**
After I use big picture, the games don't launch and when I look at the launch parameters, they are cut off

**To Reproduce**
1. Use SteamGridDB as usual
2. Launch Big Picture Mode
3. Launch a Game
4. Exit Steam
5. Open Steam again
6. Now, the games that you tried to launch in big picture before will no longer launch

**Expected behavior**
I expected the games to not break after using big picture mode

**Operating System**
 - Windows 10, 20H2

**Installed Launchers**
- Epic Games Launcher
- Origin

**Screenshots**
n/a

**Log**
You can find the log file by opening the "Run" dialog by pressing Win+R, pasting `%appdata%/steamgriddb-manager` into it then pressing "OK". Upload it here as an attachment.
[log.log](https://github.com/SteamGridDB/steamgriddb-manager/files/6760464/log.log)

**Additional context**

**Comment by kongomongo** [comment]
related to https://github.com/SteamGridDB/steamgriddb-manager/issues/89 ?

**Comment by rorokapur** [comment]
> related to #89 ?

Yes, that was the problem, some games have paths that are too long. That has nothing to do with the program and is about my system.
