### ISSUE TITLE
mismatched launchers

### ISSUE THREAD

**Issue by SpriggsyUK** [steamgriddb/steamgriddb-manager#23]
![SteamgridDB Bug](https://user-images.githubusercontent.com/21022207/63180637-9dd90500-c046-11e9-821d-0a856c5f5d79.png)

The listed launchers are missmatched in the UI and also hasn't pulled any of the actual Uplay titles on my PC in.

**Comment by doZennn** [comment]
Fixed in 0.1.2.  
You'll most likely see an error under a failed imported platform. Please make a new issue for that. Thanks!
