### ISSUE TITLE
Add support for vertical images (New Library Beta)

### ISSUE THREAD

**Issue by notNSANE** [steamgriddb/steamgriddb-manager#47]
Is this a duplicate or just that no one opened the bug? I feel this is such an obvious request, haha. 

Anyways, I wanted to use this specifically for the new Library beta but the manager it's only showing the old horizontal images.

**Comment by cooperate** [comment]
Seems like the next logical step.  Would probably bring a lot of attention to this software seeing how many games are missing the new artwork on Steam.  The website has added metadata tags for vertical images it seems ("Vertical Steam").

**Comment by parkerlreed** [comment]
So is this program only for importing games? Would be great to automate pulling into the boxart covers for the new layout. Manually one by one has been a PITA

**Comment by thundercatsNZ** [comment]
> So is this program only for importing games? Would be great to automate pulling in the boxart covers for the new layout. Manually one by one has been a PITA

You can use it for selecting artwork from steamgriddb by clicking on the entry in the Library section once you've imported it.

Would be great if this was updated asap now that there are three different artworks per game ("600x900", "hero" and "logo") and as you said, adding each manually is very time consuming.

App also needs work on game detection - only half my Origin and Uplay games are detected, but that's another issue.

**Comment by doZennn** [comment]
Fixed in v0.4.0
