### ISSUE TITLE
SteamGridDB Manager + Steam ROM Manager

### ISSUE THREAD

**Issue by noah978** [steamgriddb/steamgriddb-manager#55]
Seeing as [Steam ROM Manager](https://github.com/doZennn/steam-rom-manager) is no longer being updated for the foreseeable future, I think it would be a logical step to eventually add ROM importing functionality into SteamGridDB Manager.

I'm only mentioning this because there isn't currently a program that has the functionality of SRM and works with the newly released Steam Library. And as far as I know, no one is currently or planning on updating SRM to support it.

Obviously, this kind of integration is a massive overhaul for an application that is still in beta currently. So I'm not expecting anything. I simply think that the addition of ROM importing would make this application an incredibly powerful tool for everyone who wants to keep all of their games on steam.

**Comment by kencinder** [comment]
Just an FYI that doZennn has posted a beta of SRM on our Discord that supports the new library.

I personally would like to see the two projects stay separate, they both serve very different purposes, and combining the two would make for one bloated project to maintain.

**Comment by noah978** [comment]
That makes sense and thanks for the FYI. I’ll consider this closed then.
