### ISSUE TITLE
Latest version, wheel keeps spinning when searching for images

### ISSUE THREAD

**Issue by adelatour11** [steamgriddb/steamgriddb-manager#60]
I am using the 0.4.1 version (windows)
I have added games to steam such as Superhot (from a twitch library) or for Mario Kart 8 (from a Cemu Wii U emulator)
When i want to search for horizontal capsule the wheel keeps spinning when searching for images
Where can i find the logs on the windows version ?

**Comment by benmooney92** [comment]
Same issue here, I found the logs in "C:\Users\[UserName]\AppData\Roaming\steamgriddb-manager\log.log"

Whenever I initiate an image search I get an infinite loading wheel and this line in the log file.

`[2019-12-09 09:30:47.241] [error] UnhandledRejection Error
    at C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\steamgriddb\src\SGDB.js:56:37
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
`

**Comment by Supavitax** [comment]
I've had a quick look at this and I'm pretty sure the "app id" is being returned as null as it's not being seen correctly by a supported launcher.

**Comment by benmooney92** [comment]
Ok, having checked again this only seems to be an issue with "Non-Steam Games", they worked fine in previous versions though.
