### ISSUE TITLE
Toggle to allow old behavior: use straight shortcuts instead of PowerShell scripts

### ISSUE THREAD

**Issue by EazyCheeze1978** [steamgriddb/steamgriddb-manager#67]
First, I will say that I absolutely love this Manager app; I always will and I hope that this will not be seen as complaining.

I do get where doZennn is coming from, with the advent of PowerShell scripts for imports, that keep each individual launcher for imported games open only as long as the game itself is open; that's best for computers with pretty limited resources, and should remain the default behavior. I do very much appreciate doZennn's looking out for all computer users in this regard :)

Thing is, for those of us with somewhat beefier systems who do not have a problem with Origin, uPlay, EGS etc. remaining resident all the time, having them launch every time a game is launched still does add a short delay to the game's launch, and there is also the factor of the ease of access to the storefronts offered by said launchers before or after playing a game, which is removed by the use of the scripts.

If there were a toggle to allow the old behavior: the creation of straight shortcuts when importing games that require launchers (a la the GOG games, which of course do not require a launcher), instead of forcing the use of the auto-closing PowerShell scripts, I think that would be awesome.

Thank you! Keep up the wonderful work and have a great holiday.

**Comment by doZennn** [comment]
If the launcher is left open after closing a game, Steam won't see the game as closed since it injects the overlay into the launcher and any child processes.

**Comment by EazyCheeze1978** [comment]
Ooof! That's tough. And I guess that's the only way it can be, if one wants to run non-Steam games while still using the overlay. 

Okay, so, this is an impossible issue. The delay's not so bad after all, and if I really want the storefronts I can access the websites themselves or start the client back up.

Thank you for the clarification on why this can't work, doZennn! Closing, and keep up the wonderful work!
